config {
    type: "view",
    name: "webhook-institutions",
    description: "A view containing the institutions extracted from webhook."
}


WITH deduplicated AS (
    SELECT DISTINCT
        SPLIT(CI1_codename, ':')[OFFSET(ARRAY_LENGTH(SPLIT(CI1_codename, ':')) - 1)] AS codename,
        CI1_descricao AS description,
        CI1_org AS org,
        CI1_status AS status,
        Radius_Realms as realm
    FROM ${ref("webhook_eduroam_institutions")}
)
SELECT *
FROM deduplicated
